name: Veracode Build

on:
  repository_dispatch:
    types: [veracode-build]

jobs:
  register:
    runs-on: ubuntu-latest
    name: register
    steps:
      - name: Register build
        id: register-build
        uses: veracode/github-actions-integration-helper@v0.1.4
        with:
          action: registerBuild
          token: ${{ github.event.client_payload.token }}
          appname: ${{ github.event.client_payload.user_config.profile_name }}
          source_repository: ${{ github.event.client_payload.repository.full_name }}
          check_run_id: ${{ github.run_id }}
          check_run_name: ${{ github.workflow }}
          head_sha: ${{ github.event.client_payload.sha }}
          event_type: ${{ github.event.client_payload.event_type }}
          branch: ${{ github.event.client_payload.user_config.sandbox_scan.branch }}
          issue_trigger_flow: ${{ github.event.client_payload.user_config.issue_trigger_flow }}

  build:
    needs: register
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          
      - name: Build with Maven
        run: | 
          cd app
          mvn clean package
        
      - name: Prepare artifact
        run: |
          mkdir -p veracode-artifact
          cp app/target/verademo.war veracode-artifact/
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: veracode-artifact
          path: veracode-artifact/verademo.war
